travis:
  secure:
    BINSTAR_TOKEN: P7X4OFsFEzrCEUZeYONk3UfLbnktVqW314EPQqJBAWwU0A4DSlTCPB9NwlTev7LynGiC6LRxQr1L7Qsm5UjZclCZfrTldVnPEpNl79NmlfFK2p3zoF1nRS0q+6KBB3LFV71VtmTtcFfUOb99ZDIDPr6mJ2USiv9FpfAclcWjUCkZp8WpIS1mqi3uEsxNsozio9Ww5rgp7vY6XRY0xgQIiT1d1wOzhWfKXmHDWADGB7eOeKIXgv1lwm5u9FatUInLGMmTCtqPFYgrcYn1FhCZqKCzoXwE3C8kX4grEX6oneJ/UBvp0J4Hz9Jv3pzkrZJuHYf3FeFU4abMoqC31vsJVVA/+JSGMs1VKvLf9TS7twZvX1ez6tupspQD+KpmBmTuOdFYG7lJnNk6YMa5xXiyU7EE9ZbcQL5Ri/wZfOF0CLLG7J1zIMhKR0rTPk+Zj9W7bXdCZ6nd4La62X4+9jXP/YUUK/I11Fj829KKGj7MUp5dreh3PCNaVgRqNvIknif71URpTeEQ1B2fN7GUiD2pH9VK61mzjSrrxaXWeErKiE4vbC5wJY+imSp94zCw56Oi/hPq5zVww6aWlxcDdbTspidBAE1RTQzZa27No4OyoS/KHq/cDvkFWn2yJMtZEg5ssQL9BbwY1szPBjracVXbtCnGiWaphe6bmZICDdeIeHo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
